version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo-dev
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: ecommerce-backend
    container_name: ecommerce-backend
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/ecommerce
      MONGO_URI: mongodb://mongo:27017/ecommerce
      RAZORPAY_KEY_ID: dummy_key
      RAZORPAY_SECRET: dummy_secret
    depends_on:
      - mongo

  frontend:
    image: ecommerce-frontend
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    image: ecommerce-admin
    container_name: ecommerce-admin
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mongo_data:

