version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: ecommerce-backend
    container_name: ecommerce-backend
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/ecommerce
      MONGO_URI: mongodb://mongo:27017/ecommerce
      RAZORPAY_KEY_ID: dummy_key
      RAZORPAY_SECRET: dummy_secret
    depends_on:
      - mongo

volumes:
  mongo_data:

